baseURL = "https://navaneeth.github.io/"
languageCode = "en-us"
title = "{love to code}"
theme = ["hyde"]

[params]
    github = "https://github.com/navaneeth/"
    tagline = "{love to code}"
    twitter = "http://twitter.com/navaneethkn"
    flickr = "https://www.flickr.com/photos/navaneethkn"
    rss = "true"
    highlight = "sunburst"
    home = "blog"
    googleAnalytics = "UA-38544003-1"
    description = " "

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/navaneeth/"},
      {Name = "Twitter", URL = "https://twitter.com/navaneeth"}
  ]

